version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package

artifacts:
  files:
    - target/*.jar
    - Procfile
  name: myapp-$(date +%Y-%m-%d)gi